package com.example.booknm;

public class Venue {
    private int id;
    private String name;
    private int capacity;
    private String location;
    private String description;

    // Full constructor
    public Venue(int id, String name, int capacity, String location, String description) {
        this.id = id;
        this.name = name;
        this.capacity = capacity;
        this.location = location;
        this.description = description;
    }

    // Constructor for creating a new venue (ID is generated by the database)
    public Venue(String name, int capacity, String location, String description) {
        this(-1, name, capacity, location, description);
    }

    // --- Getters ---

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getCapacity() {
        return capacity;
    }

    public String getLocation() {
        return location;
    }

    public String getDescription() {
        return description;
    }
}
